---

- name: Install handbrake with apt
  apt:
    name: handbrake
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install handbrake with pacman
  pacman:
    name: handbrake
    state: present
  become: true
  when: ansible_distribution == "Archlinux"