---

- name: Install kid3 with apt
  apt:
    name: kid3
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install kid3 with pacman
  pacman:
    name: kid3
    state: present
  become: true
  when: ansible_distribution == "Archlinux"