---

- name: Install k3b with apt
  apt:
    name: k3b
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install k3b with pacman
  pacman:
    name: k3b
    state: present
  become: true
  when: ansible_distribution == "Archlinux"